### ISSUE TITLE
Repo contains only end version of retirement-calculator

### ISSUE THREAD

**Issue by declspec-cdecl** [PacktPublishing/Scala-Programming-Projects#1]
Repo contains only master branch and only end version of retirement-calculator. It is better to view all code at certain step

**Comment by mikaelv** [comment]
Thank you for raising this issue, my apologies for the inconvenience. 
I have moved the final version of retirement-calculator to Chapter03, and added the Chapter02's end state in Chapter02/retirement-calculator.
